modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="statistix"
version="${file.jarVersion}" 
displayName="Statistix"
# updateJSONURL="https://github.com/JBoerrigter/Statistix" #optional
# displayURL="https://github.com/JBoerrigter/Statistix" #optional
# logoFile="statistix.png" #optional
credits="powered by JBoerrigter"
authors="CyrixXx"
description="With this mod you´re able to post your statistics to the server"

# Forge
[[dependencies.examplemod]] 
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.statistix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
